#!/bin/env bash

 target="uinput-nes/src/main.h"
gitroot=$(git rev-parse --show-toplevel 2> /dev/null)

[ $? != 0 ] && exit

rev=$(git describe --tags 2> /dev/null)
echo "Updating to v$rev"

sed --in-place "s/\(#define.*VERSION.*\)\".*\"/\1\"$rev\"/" \
    "$gitroot/$target"
